# Black Scholes Merton Monte Carlo Simulation

 

 

S0 Initial Stock Index Level S0=100
K Strike Price for European option K=105
T Time to Maturity  T= 1 year
r risk free interest rate - r= 0.05
σ Constant volatility    σ =0.2
z Standard normally distributed random variable
z(i) , i ∈ {1,2, ... I}
I = 100000

## Algorithm for Monte Carlo validation procedure

1. Draw I pseudo random numbers z(i) i ∈ {1,2, ... I} from the standard normal distribution
2. Calculate all resultin index level at maturity ST(i) for any given z(i) and Equation 1
3. Calculate all inner values of the option at maturity as hT(i) = max(ST(i) - K, 0)
4. Estimate the option value via the Monte Carlo Estimator as given in equation 2


 

 


In [16]:
import math
import numpy as np

#Paramerter Values:
S0 =100 # initial index level
K = 105 # strike price
T = 0.11 # time to maturity
r = 0.05 # risk free short rate
sigma = 0.2 # volatility

I = 100000

#Valuation algorithm

np.random.seed(1000)
z = np.random.standard_normal(I) # pseudo random numbers

#Index level at maturity

ST = S0 * np.exp((r-0.5*sigma**2)*T + sigma * math.sqrt(T)*z)
ht = np.maximum(ST - K, 0)  # payoff at maturity
C0 = math.exp(-r*T)*np.mean(ht)  #Monte Carlo Estimator

# Print Results
print('Value of European call option %5.3f.' % C0)



Value of European call option 1.050.


In [17]:
z

array([-0.8044583 ,  0.32093155, -0.02548288, ...,  2.05563421,
       -0.31621237, -0.19326188])

In [18]:
ST

array([ 95.11707097, 102.48929729, 100.16109531, ..., 114.98774228,
        98.24801338,  99.05256247])

In [19]:
type(ST)

numpy.ndarray

In [20]:
ht

array([0.        , 0.        , 0.        , ..., 9.98774228, 0.        ,
       0.        ])

In [21]:
ht.ndim

1

In [22]:
ht.size

100000

In [23]:
np.average(ST)

100.52939991502807